LiveSmart/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('resolution/', include('resolution.urls')),
]

resolution/urls.py
from django.urls import path
from . import views

app_name = 'resolution'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    #user registration
    path('register/', views.UserFormView.as_view(), name='register'),


    path('<pk>/', views.DetailView.as_view(), name="detail"),

    # add resolution -  /resolution/resolution/add/
    path('resolution/add/$', views.ResolutionCreate.as_view(), name='resolution-add'),

    # edit resolutions - /resolution/resolution/2/
    path('resolution/<pk>/$', views.ResolutionUpdate.as_view(), name='resolution-update'),

    # delete resolution - /resolution/resolution/2/delete
    path('resolution/<pk>/delete/$', views.ResolutionDelete.as_view(), name='resolution-delete'),
]

resolution/models.py
from django.db import models
from django.urls import reverse


class YourResolutions(models.Model):
    resolution_title = models.CharField(max_length=100)
    resolution_category = models.CharField(max_length=100)
    resolution_year = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('resolution:index')

    def __str__(self):
        return self.resolution_title + ' - ' + self.resolution_category +' - '+ self.resolution_year

class notes(models.Model):
    yourresolution = models.ForeignKey(YourResolutions, on_delete=models.CASCADE)
    note_title = models.CharField(max_length=500)
    note_content = models.CharField(max_length=5000)

    def __str__(self):
        return self.note_title

resolution/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields=['username', 'email', 'password']

resolution/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from .models import YourResolutions



class IndexView(generic.ListView):
    template_name = 'resolution/index.html'

    def get_queryset(self):
        return YourResolutions.objects.all()


class DetailView(generic.DetailView):
    model = YourResolutions
    template_name = 'resolution/detail.html'



class ResolutionCreate(CreateView):
    model = YourResolutions
    fields = ['resolution_title', 'resolution_category', 'resolution_year']


class ResolutionUpdate(UpdateView):
    model = YourResolutions
    fields = ['resolution_title', 'resolution_category', 'resolution_year']


class ResolutionDelete(DeleteView):
    model = YourResolutions
    success_url = reverse_lazy('resolution:index')


class UserFormView(View):
    form_class = UserForm
    template_name = 'resolution/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # add user to database
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if cridentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('resolution:index')
        return render(request, self.template_name, {'form':form})

resolution/templates/resolution/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'resolution/style.css' %}" />
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-default">
  <div class="container-fluid">

        <!-- LOGO -->
        <div class="navbar-header">
            <a id="logo" class="navbar-brand" href="{% url 'resolution:index' %}"><img src='{% static "resolution/images/livesmartLogo.png" %}'/></a>
            <a class="navbar-brand" href="{% url 'resolution:index' %}">Home</a>
            <a class="navbar-brand" href="{% url 'resolution:resolution-add' %}">Add resolution</a>
            <a class="navbar-brand" href="{% url 'resolution:register' %}">Register</a>
            <a class="navbar-brand" href="{% url 'admin:login' %}">Login</a>
            <a class="navbar-brand" href="{% url 'admin:logout' %}">Logout</a>
        </div>

  </div>
</nav>

{% block body %}
{% endblock %}

resolution/templates/resolution/detail.html
{% extends 'resolution/base.html' %}

{% block body %}
<h1>{{ note.resolution_title }}</h1>
<h2> {{ note.resolution_category }} </h2>



<ul class="list-group">
  {% for res in yourresolutions.notes_set.all %}
        <li class="list-group-item">{{ res.note_title }} - {{ res.note_content }}</li>
  {% endfor %}
</ul>
{% endblock %}

resolution/templates/resolution/form-template.html
{% for field in form  %}

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2" > {{ field.label_tag }} </label>
    <div class="col-sm-10">{{ field }}</div>
  </div>

{% endfor %}

resolution/templates/resolution/index.html
{% extends 'resolution/base.html' %}

{% block body %}
{% if object_list %}
<h3>Here are all your resolutions for this year</h3>
<ul class="list-group">
  {% for result in object_list %}
  <li class="list-group-item"><a class="list-group-item" href="{% url 'resolution:detail' result.id %}">{{result.resolution_title}}</a><br> <a class="icon update" href="{% url 'resolution:resolution-update' result.id %}"> <i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
    <form action="{% url 'resolution:resolution-delete' result.id %}" method="post" style="display:inline-block">
      {% csrf_token %}
      <input type="hidden" name="resolution_id" value="{{ result.id }}"/>
      <button type="submit" class="btn btn-default btn-sm">
          <i class="fa fa-trash" aria-hidden="true"></i>
      </button>
    </form>
  </li>
  {% endfor %}
</ul>

{% else %}
  <h3>No results to be displayed</h3>
{% endif %}
{% endblock %}

resolution/templates/resolution/registration_form.html
{% extends 'resolution/base.html' %}
{% block title %}Register{% endblock %}

{%block body%}

<div class="container-fluid">

    <div class="row">

          <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
              <div class="panel-body">
                  <h3> Create New Account </h3>
                  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {%include "resolution/form-template.html"%}
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>
                  </form>
              </div>
            </div>
          </div>

      </div>
  </div>

  {% endblock %}

resolution/templates/resolution/yourresolutions_form.html
{% extends 'resolution/base.html' %}
{% block title %}Add new resolution{% endblock %}

{%block body%}

<div class="container-fluid">

    <div class="row">

          <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
              <div class="panel-body">

                  <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {%include "resolution/form-template.html"%}
                    <div class="form-group">
                      <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                      </div>
                    </div>
                  </form>
              </div>
            </div>
          </div>

      </div>
  </div>

  {% endblock %}